library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(ggplot2)
library(forecast)
library(plotly)
library(timetk)
library(shinyjs)
library(dplyr)
library(data.table)
library(tseries)
library(magrittr)
library(urca)
library(ggfortify)
library(dashboardthemes)

source("ui.R")
source("server.R")

shinyApp(ui = ui, server = server)